apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: strawberry-tools
  name: website
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: "ghcr.io/strawberry-tools/website:latest"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: strawberry-tools
  name: website
  labels:
    app: website
spec:
  type: ClusterIP
  selector:
    app: website
  ports:
    - protocol: TCP
      name: http
      port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: strawberry-tools
  name: website
  labels:
    app: website
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/preserve-trailing-slash: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - www.strawberry.tools
    - strawberry.tools
    secretName: website-tls
  rules:
  - host: www.strawberry.tools
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: website
            port:
              number: 80
